
// /*fun main() {
//     var a=1
//     var b=2
//     println(a+b)
//     val c=2
//     val d=3
//     print(c+d)
// }*/
// // fun main(){
// //     var a:Int
// //     a=10
// //     val b=10
// //     var c:Int
// //     c=a+b
// //     print("------"+c+"-----")
// //     var A=20
// //     print(A)
// //     var ____a=40
// //     print(____a)
// //     var string=40
// //     print(string)
// // //  white space is not allowed in variABLE
// //     var INTEGER=40
// //     print(INTEGER)
// // }
// // fun main(){
// //     var age: Int=25
// //     println(age)
// // }
// // class Person{
// //     var name: String="john doe"
// //     val age: Int =30
// //     fun displayInfo(){
// //         println("Name: $name,Age: $age")
        
// //     }
// // }
// // fun main(){
// //     val person=Person()
// //     person.displayInfo()
// // }

// // fun greet(){
// //     val message:String="hello kotlin"
// //     println(message)
// // }
// // fun main(){
// //     val a=10
// //     val b=20
// //     val result="sum of $a a  b is  ${a+b}"
// //     println(result)
// // }
// // fun main(){
// //     var n=-2;
// //     if(n<0){
// //         println("it is smaller")
// //     }
// // }

// // fun main(){
// //     val letter: char
// //     letter='A'
// //     println("$letter")
// //     print('\n')
// //     print('\$')
// // }


// // fun main(){
// //     val numbers=arrayOf(1,2,3,4,5)
    
// // //     print(numbers[0])
// // //     print(numbers[1])
// // //     print(numbers[2])
// // //     print(numbers[3])
// // //     print(numbers[4])
// // //     val words: Array<String>=arrayOf("kotlin","java","python")
// // //     val squares=Array(5) {i->i*i}
// //     val size= numbers.size
// //     println("size of numbers array: $size")
// //     if(numbers.isEmpty()){
// //         print
// //     }
    
// // }


// multidimensional array
fun main(){
    val matrix:
}